/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test/test.check" instead.
 */

#include <check.h>
#include <stdio.h>

#include "./../brick_game/tetris/backend.h"
#include "./../brick_game/tetris/common.h"

START_TEST(test1) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[17][0] = 2, game->field[17][1] = 2, game->field[17][2] = 2,
  game->field[17][3] = 4, game->field[17][4] = 4, game->field[17][6] = 6,
  game->field[17][7] = 6, game->field[16][7] = 6, game->field[17][8] = 2,
  game->field[17][9] = 2, game->field[18][0] = 2, game->field[18][1] = 2,
  game->field[18][2] = 2, game->field[18][3] = 4, game->field[18][4] = 4,
  game->field[18][5] = 2, game->field[18][6] = 6, game->field[18][7] = 5,
  game->field[18][8] = 5, game->field[18][9] = 1, game->field[19][0] = 4,
  game->field[19][1] = 4, game->field[19][2] = 2, game->field[19][3] = 2,
  game->field[19][4] = 2, game->field[19][5] = 2, game->field[19][6] = 5,
  game->field[19][7] = 5, game->field[19][8] = 7, game->field[19][9] = 2,
  game->field[20][0] = 4, game->field[20][1] = 4, game->field[20][2] = 2,
  game->field[20][3] = 1, game->field[20][4] = 1, game->field[20][5] = 1,
  game->field[20][6] = 1, game->field[20][7] = 7, game->field[20][8] = 7,
  game->field[20][9] = 7;
  check_field(game);
  ck_assert_int_eq(game->score, THREE_LINES);
  ck_assert_int_eq(game->level, 2);
  for (int i = 0; i < FIELD_HEIGHT - 3; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      ck_assert_int_eq(game->field[i][j], EMPTY_PLACE);
    }
  }
  ck_assert_int_eq(game->field[19][7], 6);
  ck_assert_int_eq(game->field[20][0], 2);
  ck_assert_int_eq(game->field[20][1], 2);
  ck_assert_int_eq(game->field[20][2], 2);
  ck_assert_int_eq(game->field[20][3], 4);
  ck_assert_int_eq(game->field[20][4], 4);
  ck_assert_int_eq(game->field[20][5], EMPTY_PLACE);
  ck_assert_int_eq(game->field[20][6], 6);
  ck_assert_int_eq(game->field[20][7], 6);
  ck_assert_int_eq(game->field[20][8], 2);
  ck_assert_int_eq(game->field[20][9], 2);
  free_game(game);
}
END_TEST

START_TEST(test2) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[20][0] = 4, game->field[20][1] = 4, game->field[20][2] = 2,
  game->field[20][3] = 1, game->field[20][4] = 1, game->field[20][5] = 1,
  game->field[20][6] = 1, game->field[20][7] = 7, game->field[20][8] = 7,
  game->field[20][9] = 7;
  check_field(game);
  ck_assert_int_eq(game->score, ONE_LINE);
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      ck_assert_int_eq(game->field[i][j], EMPTY_PLACE);
    }
  }
  free_game(game);
}
END_TEST

START_TEST(test3) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[19][0] = 4, game->field[19][1] = 4, game->field[19][2] = 2,
  game->field[19][3] = 2, game->field[19][4] = 2, game->field[19][5] = 2,
  game->field[19][6] = 5, game->field[19][7] = 5, game->field[19][8] = 7,
  game->field[19][9] = 2, game->field[20][0] = 4, game->field[20][1] = 4,
  game->field[20][2] = 2, game->field[20][3] = 1, game->field[20][4] = 1,
  game->field[20][5] = 1, game->field[20][6] = 1, game->field[20][7] = 7,
  game->field[20][8] = 7, game->field[20][9] = 7;
  check_field(game);
  ck_assert_int_eq(game->score, TWO_LINES);
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      ck_assert_int_eq(game->field[i][j], EMPTY_PLACE);
    }
  }
  free_game(game);
}
END_TEST

START_TEST(test4) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  for (int i = 17; i < FIELD_HEIGHT - 1; ++i) {
    for (int j = 0; j < FIELD_WIDTH - 1; ++j) {
      game->field[i][j] = 5 + MOVING_PLACE + 1;
    }
  }
  check_field(game);
  ck_assert_int_eq(game->score, FOUR_LINES);
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      ck_assert_int_eq(game->field[i][j], EMPTY_PLACE);
    }
  }
  free_game(game);
}
END_TEST

START_TEST(test5) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  figure->figure = 4;
  figure->x = 1, figure->y = 0, figure->rotation = 0;
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[1][4] = MOVING_PLACE + figure->figure + 1;
  game->field[1][5] = MOVING_PLACE + figure->figure + 1;
  game->field[2][4] = MOVING_PLACE + figure->figure + 1;
  game->field[2][3] = MOVING_PLACE + figure->figure + 1;
  shift_figure(figure, game);
  ck_assert_int_eq(game->field[1][4], EMPTY_PLACE);
  ck_assert_int_eq(game->field[1][5], EMPTY_PLACE);
  ck_assert_int_eq(game->field[2][3], EMPTY_PLACE);

  ck_assert_int_eq(game->field[2][4], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][5], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[3][4], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[3][3], MOVING_PLACE + figure->figure + 1);
  free_game(game);
}
END_TEST

START_TEST(test6) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  figure->figure = 0, figure->x = 19, figure->y = 0;
  game->field[19][3] = MOVING_PLACE + figure->figure + 1,
  game->field[19][4] = MOVING_PLACE + figure->figure + 1,
  game->field[19][5] = MOVING_PLACE + figure->figure + 1,
  game->field[19][6] = MOVING_PLACE + figure->figure + 1;
  fix_figure(figure, game);
  ck_assert_int_eq(game->field[19][3], figure->figure + 1);
  ck_assert_int_eq(game->field[19][4], figure->figure + 1);
  ck_assert_int_eq(game->field[19][5], figure->figure + 1);
  ck_assert_int_eq(game->field[19][6], figure->figure + 1);
}
END_TEST

START_TEST(test7) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  figure->figure = 6;
  figure->x = 1, figure->y = 0, figure->rotation = 0;
  game->pause = fall;
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[1][4] = MOVING_PLACE + figure->figure + 1;
  game->field[2][3] = MOVING_PLACE + figure->figure + 1;
  game->field[2][4] = MOVING_PLACE + figure->figure + 1;
  game->field[2][5] = MOVING_PLACE + figure->figure + 1;
  updateCurrentState();
  game->pause = fall;
  updateCurrentState();
  ck_assert_int_eq(game->field[1][4], EMPTY_PLACE);
  ck_assert_int_eq(game->field[2][3], EMPTY_PLACE);
  ck_assert_int_eq(game->field[2][4], EMPTY_PLACE);
  ck_assert_int_eq(game->field[2][5], EMPTY_PLACE);
  ck_assert_int_eq(game->field[19][4], 7);
  ck_assert_int_eq(game->field[20][4], 7);
  ck_assert_int_eq(game->field[20][3], 7);
  ck_assert_int_eq(game->field[20][5], 7);
  free_game(game);
}
END_TEST

START_TEST(test8) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  figure->figure = 5;
  figure->x = 1, figure->y = 0, figure->rotation = 0;
  game->pause = rotation;
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[1][4] = MOVING_PLACE + figure->figure + 1;
  game->field[1][3] = MOVING_PLACE + figure->figure + 1;
  game->field[2][4] = MOVING_PLACE + figure->figure + 1;
  game->field[2][5] = MOVING_PLACE + figure->figure + 1;

  updateCurrentState();
  game->pause = rotation;
  updateCurrentState();
  game->pause = rotation;
  updateCurrentState();
  ck_assert_int_eq(game->field[1][3], EMPTY_PLACE);
  ck_assert_int_eq(game->field[2][5], EMPTY_PLACE);
  ck_assert_int_eq(game->field[1][4], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][4], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][3], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[3][3], MOVING_PLACE + figure->figure + 1);
  free_game(game);
}
END_TEST

START_TEST(test9) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  figure->figure = 6;
  figure->x = 1, figure->y = 0, figure->rotation = 0;
  game->pause = move_right;
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[1][4] = MOVING_PLACE + figure->figure + 1;
  game->field[2][3] = MOVING_PLACE + figure->figure + 1;
  game->field[2][4] = MOVING_PLACE + figure->figure + 1;
  game->field[2][5] = MOVING_PLACE + figure->figure + 1;
  updateCurrentState();
  game->pause = move_right;
  updateCurrentState();
  game->pause = move_right;
  updateCurrentState();
  ck_assert_int_eq(game->field[1][7], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[1][4], EMPTY_PLACE);
  ck_assert_int_eq(game->field[2][6], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][7], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][8], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][3], EMPTY_PLACE);
  ck_assert_int_eq(game->field[2][4], EMPTY_PLACE);
  ck_assert_int_eq(game->field[2][5], EMPTY_PLACE);
  free_game(game);
}
END_TEST

START_TEST(test10) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  figure->figure = 6;
  figure->x = 1, figure->y = 0, figure->rotation = 0;
  game->pause = move_left;
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[1][4] = MOVING_PLACE + figure->figure + 1;
  game->field[2][3] = MOVING_PLACE + figure->figure + 1;
  game->field[2][4] = MOVING_PLACE + figure->figure + 1;
  game->field[2][5] = MOVING_PLACE + figure->figure + 1;
  updateCurrentState();
  game->pause = move_left;
  updateCurrentState();
  game->pause = move_left;
  updateCurrentState();
  ck_assert_int_eq(game->field[1][1], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][0], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][1], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][2], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][3], EMPTY_PLACE);
  ck_assert_int_eq(game->field[2][4], EMPTY_PLACE);
  ck_assert_int_eq(game->field[2][5], EMPTY_PLACE);
  ck_assert_int_eq(game->field[1][4], EMPTY_PLACE);
  free_game(game);
}
END_TEST

START_TEST(test11) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  figure->figure = 0;
  figure->x = 3, figure->y = -5, figure->rotation = 1;
  game->pause = rotation;
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[2][0] = MOVING_PLACE + figure->figure + 1,
  game->field[3][0] = MOVING_PLACE + figure->figure + 1,
  game->field[4][0] = MOVING_PLACE + figure->figure + 1,
  game->field[5][0] = MOVING_PLACE + figure->figure + 1;
  updateCurrentState();
  game->pause = rotation;
  updateCurrentState();
  game->pause = rotation;
  updateCurrentState();
  ck_assert_int_eq(game->field[2][0], EMPTY_PLACE);

  ck_assert_int_eq(game->field[4][0], EMPTY_PLACE);
  ck_assert_int_eq(game->field[5][0], EMPTY_PLACE);
  ck_assert_int_eq(game->field[3][0], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[3][1], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[3][2], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[3][3], MOVING_PLACE + figure->figure + 1);
  free_game(game);
}
END_TEST

START_TEST(test12) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  figure->figure = 0;
  figure->x = 2, figure->y = -4, figure->rotation = 1;
  game->pause = rotation;
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[1][1] = MOVING_PLACE + figure->figure + 1,
  game->field[2][1] = MOVING_PLACE + figure->figure + 1,
  game->field[3][1] = MOVING_PLACE + figure->figure + 1,
  game->field[4][1] = MOVING_PLACE + figure->figure + 1;
  updateCurrentState();
  game->pause = rotation;
  updateCurrentState();
  game->pause = rotation;
  updateCurrentState();
  ck_assert_int_eq(game->field[1][1], EMPTY_PLACE);
  ck_assert_int_eq(game->field[3][1], EMPTY_PLACE);
  ck_assert_int_eq(game->field[4][1], EMPTY_PLACE);

  ck_assert_int_eq(game->field[2][0], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][1], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][2], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[2][3], MOVING_PLACE + figure->figure + 1);
  free_game(game);
}
END_TEST

START_TEST(test13) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  figure->figure = 0;
  figure->x = 3, figure->y = -3, figure->rotation = 3;
  game->pause = rotation;
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[2][1] = MOVING_PLACE + figure->figure + 1,
  game->field[3][1] = MOVING_PLACE + figure->figure + 1,
  game->field[4][1] = MOVING_PLACE + figure->figure + 1,
  game->field[5][1] = MOVING_PLACE + figure->figure + 1;
  updateCurrentState();
  game->pause = rotation;
  updateCurrentState();
  game->pause = rotation;
  updateCurrentState();
  ck_assert_int_eq(game->field[2][1], EMPTY_PLACE);
  ck_assert_int_eq(game->field[3][1], EMPTY_PLACE);
  ck_assert_int_eq(game->field[5][1], EMPTY_PLACE);

  ck_assert_int_eq(game->field[4][0], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[4][1], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[4][2], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[4][3], MOVING_PLACE + figure->figure + 1);
  free_game(game);
}
END_TEST

START_TEST(test14) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  figure->figure = 0;
  figure->x = 3, figure->y = -4, figure->rotation = 3;
  game->pause = rotation;
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[2][0] = MOVING_PLACE + figure->figure + 1,
  game->field[3][0] = MOVING_PLACE + figure->figure + 1,
  game->field[4][0] = MOVING_PLACE + figure->figure + 1,
  game->field[5][0] = MOVING_PLACE + figure->figure + 1;
  updateCurrentState();
  game->pause = rotation;
  updateCurrentState();
  game->pause = rotation;
  updateCurrentState();
  ck_assert_int_eq(game->field[2][1], EMPTY_PLACE);
  ck_assert_int_eq(game->field[3][1], EMPTY_PLACE);
  ck_assert_int_eq(game->field[5][1], EMPTY_PLACE);

  ck_assert_int_eq(game->field[4][0], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[4][1], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[4][2], MOVING_PLACE + figure->figure + 1);
  ck_assert_int_eq(game->field[4][3], MOVING_PLACE + figure->figure + 1);
  free_game(game);
}
END_TEST

START_TEST(test15) {
  GameInfo_t *game = set_game_info();
  userInput(Start, 0);
  ck_assert_int_eq(game->pause, shift);
  free_game(game);
}
END_TEST

START_TEST(test16) {
  GameInfo_t *game = set_game_info();
  userInput(Pause, 0);
  ck_assert_int_eq(game->pause, pause);
  free_game(game);
}
END_TEST

START_TEST(test17) {
  GameInfo_t *game = set_game_info();
  userInput(Terminate, 0);
  ck_assert_int_eq(game->pause, terminate);
  free_game(game);
}
END_TEST

START_TEST(test18) {
  GameInfo_t *game = set_game_info();
  userInput(Left, 0);
  ck_assert_int_eq(game->pause, move_left);
  free_game(game);
}
END_TEST

START_TEST(test19) {
  GameInfo_t *game = set_game_info();
  userInput(Right, 0);
  ck_assert_int_eq(game->pause, move_right);
  free_game(game);
}
END_TEST

START_TEST(test20) {
  GameInfo_t *game = set_game_info();
  userInput(Down, 0);
  ck_assert_int_eq(game->pause, fall);
  free_game(game);
}
END_TEST

START_TEST(test21) {
  GameInfo_t *game = set_game_info();
  userInput(Action, 0);
  ck_assert_int_eq(game->pause, rotation);
  free_game(game);
}
END_TEST

START_TEST(test22) {
  GameInfo_t *game = set_game_info();
  game->pause = ready_to_start;
  userInput(Up, 0);
  ck_assert_int_eq(game->pause, ready_to_start);
  free_game(game);
}
END_TEST

START_TEST(test23) {
  GameInfo_t *game = set_game_info();
  game->pause = no_signal;
  userInput(Up, 0);
  game->pause = no_signal;
  userInput(Up, 0);
  ck_assert_int_eq(game->pause, no_signal);
  free_game(game);
}
END_TEST

START_TEST(test24) {
  GameInfo_t *game = set_game_info();
  game->pause = terminate;
  userInput(Up, 0);
  game->pause = terminate;
  userInput(Up, 0);
  ck_assert_int_eq(game->pause, terminate);
  free_game(game);
}
END_TEST

START_TEST(test25) {
  GameInfo_t *game = set_game_info();
  game->pause = no_signal;
  userInput(Up, 0);
  game->pause = pause;
  userInput(Start, 0);
  ck_assert_int_eq(game->pause, no_signal);
  free_game(game);
}
END_TEST

START_TEST(test26) {
  GameInfo_t *game = set_game_info();
  game->pause = ready_to_start;
  userInput(Up, 0);
  game->pause = move_left;
  userInput(Up, 0);
  ck_assert_int_eq(game->pause, no_signal);
  free_game(game);
}
END_TEST

START_TEST(test27) {
  GameInfo_t *game = set_game_info();
  game->pause = no_signal;
  userInput(Up, 0);
  game->pause = pause;
  userInput(Action, 0);
  ck_assert_int_eq(game->pause, pause);
  free_game(game);
}
END_TEST

START_TEST(test28) {
  GameInfo_t *game = set_game_info();
  game->pause = no_signal;
  userInput(Up, 0);
  game->pause = pause;
  userInput(Terminate, 0);
  ck_assert_int_eq(game->pause, terminate);
  free_game(game);
}
END_TEST

START_TEST(test29) {
  GameInfo_t *game = set_game_info();
  Figure_position *figure = set_figure_info();
  init_game(game, figure);
  for (int i = 0; i < FIELD_HEIGHT; ++i) {
    for (int j = 0; j < FIELD_WIDTH; ++j) {
      game->field[i][j] = EMPTY_PLACE;
    }
  }
  game->field[0][5] = 3;
  check_field(game);
  ck_assert_int_eq(game->pause, game_over);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test1);
  tcase_add_test(tc1_1, test2);
  tcase_add_test(tc1_1, test3);
  tcase_add_test(tc1_1, test4);
  tcase_add_test(tc1_1, test5);
  tcase_add_test(tc1_1, test6);
  tcase_add_test(tc1_1, test7);
  tcase_add_test(tc1_1, test8);
  tcase_add_test(tc1_1, test9);
  tcase_add_test(tc1_1, test10);
  tcase_add_test(tc1_1, test11);
  tcase_add_test(tc1_1, test12);
  tcase_add_test(tc1_1, test13);
  tcase_add_test(tc1_1, test14);
  tcase_add_test(tc1_1, test15);
  tcase_add_test(tc1_1, test16);
  tcase_add_test(tc1_1, test17);
  tcase_add_test(tc1_1, test18);
  tcase_add_test(tc1_1, test19);
  tcase_add_test(tc1_1, test20);
  tcase_add_test(tc1_1, test21);
  tcase_add_test(tc1_1, test22);
  tcase_add_test(tc1_1, test23);
  tcase_add_test(tc1_1, test24);
  tcase_add_test(tc1_1, test25);
  tcase_add_test(tc1_1, test26);
  tcase_add_test(tc1_1, test27);
  tcase_add_test(tc1_1, test28);
  tcase_add_test(tc1_1, test29);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
